name = "vidpod-media-jobs"
main = "src/index.ts"
compatibility_date = "2026-04-13"
workers_dev = false

[[routes]]
pattern = "vidpod-jobs.nlewis.dev"
custom_domain = true

[[queues.producers]]
queue = "vidpod-media-jobs"
binding = "MEDIA_JOBS"

[[queues.consumers]]
queue = "vidpod-media-jobs"
max_batch_size = 1
max_batch_timeout = 2
max_retries = 3

[env.dev]
name = "vidpod-media-jobs-dev"
workers_dev = true
routes = []

[[env.dev.queues.producers]]
queue = "vidpod-media-jobs-dev"
binding = "MEDIA_JOBS"

[[env.dev.queues.consumers]]
queue = "vidpod-media-jobs-dev"
max_batch_size = 1
max_batch_timeout = 2
max_retries = 3
