name = "vidpod-media-jobs"
main = "src/index.ts"
compatibility_date = "2026-04-13"
workers_dev = false

[[routes]]
pattern = "vidpod-jobs.nlewis.dev"
custom_domain = true

[[durable_objects.bindings]]
name = "MP4_EXPORT_JOB"
class_name = "Mp4ExportJob"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "TRANSCRIPT_JOB"
class_name = "TranscriptJob"

[[queues.producers]]
queue = "vidpod-media-jobs"
binding = "MEDIA_JOBS"

[[queues.consumers]]
queue = "vidpod-media-jobs"
max_batch_size = 1
max_batch_timeout = 2
max_retries = 3

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Mp4ExportJob"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["TranscriptJob"]

[env.dev]
name = "vidpod-media-jobs-dev"
workers_dev = true
routes = []

[env.dev.ai]
binding = "AI"

[[env.dev.durable_objects.bindings]]
name = "MP4_EXPORT_JOB"
class_name = "Mp4ExportJob"

[[env.dev.durable_objects.bindings]]
name = "TRANSCRIPT_JOB"
class_name = "TranscriptJob"

[[env.dev.queues.producers]]
queue = "vidpod-media-jobs-dev"
binding = "MEDIA_JOBS"

[[env.dev.queues.consumers]]
queue = "vidpod-media-jobs-dev"
max_batch_size = 1
max_batch_timeout = 2
max_retries = 3
